// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lab1mvc.context;

#nullable disable

namespace lab1mvc.Migrations
{
    [DbContext(typeof(dblab1))]
    [Migration("20251012122227_Studnts")]
    partial class Studnts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("lab1mvc.Models.Student", b =>
                {
                    b.Property<int>("SSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SSN"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SSN");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            SSN = 1,
                            Address = "giza,egypt",
                            Age = 20,
                            Email = "hamza@yahoo.com",
                            Image = "hamza.jpg",
                            Name = "Hamza Khaled"
                        },
                        new
                        {
                            SSN = 2,
                            Address = "fayuom",
                            Age = 22,
                            Email = "Gohary@yahoo.com",
                            Image = "Gohary.jpg",
                            Name = "Gohary"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
